//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ParticleCableConstraint : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParticleCableConstraint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ParticleCableConstraint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParticleCableConstraint() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_ParticleCableConstraint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool AddContact(ParticleContact contact, uint limit) {
    bool ret = PhysicsEngineForFunPINVOKE.ParticleCableConstraint_AddContact(swigCPtr, ParticleContact.getCPtr(contact), limit);
    return ret;
  }

  public float maxLength {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCableConstraint_maxLength_set(swigCPtr, value);
    } 
    get {
      float ret = PhysicsEngineForFunPINVOKE.ParticleCableConstraint_maxLength_get(swigCPtr);
      return ret;
    } 
  }

  public float restitutionCoefficient {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCableConstraint_restitutionCoefficient_set(swigCPtr, value);
    } 
    get {
      float ret = PhysicsEngineForFunPINVOKE.ParticleCableConstraint_restitutionCoefficient_get(swigCPtr);
      return ret;
    } 
  }

  public Particle particle {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCableConstraint_particle_set(swigCPtr, Particle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.ParticleCableConstraint_particle_get(swigCPtr);
      Particle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Particle(cPtr, false);
      return ret;
    } 
  }

  public Vector3 anchorPoint {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCableConstraint_anchorPoint_set(swigCPtr, Vector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.ParticleCableConstraint_anchorPoint_get(swigCPtr);
      Vector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3(cPtr, false);
      return ret;
    } 
  }

  public ParticleCableConstraint() : this(PhysicsEngineForFunPINVOKE.new_ParticleCableConstraint(), true) {
  }

}
