//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ParticleCable : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParticleCable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ParticleCable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParticleCable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_ParticleCable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool AddContact(ParticleContact contact, uint limit) {
    bool ret = PhysicsEngineForFunPINVOKE.ParticleCable_AddContact(swigCPtr, ParticleContact.getCPtr(contact), limit);
    return ret;
  }

  public float maxLength {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCable_maxLength_set(swigCPtr, value);
    } 
    get {
      float ret = PhysicsEngineForFunPINVOKE.ParticleCable_maxLength_get(swigCPtr);
      return ret;
    } 
  }

  public float restitutionCoefficient {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCable_restitutionCoefficient_set(swigCPtr, value);
    } 
    get {
      float ret = PhysicsEngineForFunPINVOKE.ParticleCable_restitutionCoefficient_get(swigCPtr);
      return ret;
    } 
  }

  public Particle particle0 {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCable_particle0_set(swigCPtr, Particle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.ParticleCable_particle0_get(swigCPtr);
      Particle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Particle(cPtr, false);
      return ret;
    } 
  }

  public Particle particle1 {
    set {
      PhysicsEngineForFunPINVOKE.ParticleCable_particle1_set(swigCPtr, Particle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.ParticleCable_particle1_get(swigCPtr);
      Particle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Particle(cPtr, false);
      return ret;
    } 
  }

  public ParticleCable() : this(PhysicsEngineForFunPINVOKE.new_ParticleCable(), true) {
  }

}
