%module PhysicsEngineForFun

%{
	#include "ParticleWorld.h"
%}

struct Vector3
{
public:
	Vector3() : x(0), y(0), z(0) {}
	Vector3(const float x, const float y, const float z)
		: x(x), y(y), z(z) {}
	float x, y, z;
};

class Particle
{
public:
	void SetMass(float mass);
	float GetMass() const;
	void Integrate(float duration);
	void AddForce(const Vector3 &force);

	Vector3 position;
	Vector3 velocity;
	Vector3 acceleration;
	float damping;
};

class ParticleContact
{
public:
	ParticleContact(Particle* a, Particle* b);
	void Resolve(float duration);
	float CalculateSeparatingVelocity() const;
	float restitutionCoefficient;
	float penetrationDepth;
	Vector3 contactNormal;
};

class ParticleCable
{
public:
	ParticleCable(Particle * a, Particle * b);
	bool AddContact(ParticleContact *contact,
	unsigned int limit) const;
	float maxLength;
	float restitutionCoefficient;
};

class ParticleCableConstraint 
{
public:
	ParticleCableConstraint(Particle * a, const Vector3 &b);
	bool AddContact(ParticleContact *contact,
		unsigned int limit) const;
	float maxLength;
	float restitutionCoefficient;
};