/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_PhysicsEngineForFun(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_PhysicsEngineForFun(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_PhysicsEngineForFun(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


	#include "ParticleWorld.h"
	#include "ParticleConstraint.h"
	#include "ParticleLink.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_Vector3__SWIG_0() {
  void * jresult ;
  Vector3 *result = 0 ;
  
  result = (Vector3 *)new Vector3();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Vector3__SWIG_1(float jarg1, float jarg2, float jarg3) {
  void * jresult ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  Vector3 *result = 0 ;
  
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (Vector3 *)new Vector3(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Vector3_x_set(void * jarg1, float jarg2) {
  Vector3 *arg1 = (Vector3 *) 0 ;
  float arg2 ;
  
  arg1 = (Vector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_Vector3_x_get(void * jarg1) {
  float jresult ;
  Vector3 *arg1 = (Vector3 *) 0 ;
  float result;
  
  arg1 = (Vector3 *)jarg1; 
  result = (float) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Vector3_y_set(void * jarg1, float jarg2) {
  Vector3 *arg1 = (Vector3 *) 0 ;
  float arg2 ;
  
  arg1 = (Vector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_Vector3_y_get(void * jarg1) {
  float jresult ;
  Vector3 *arg1 = (Vector3 *) 0 ;
  float result;
  
  arg1 = (Vector3 *)jarg1; 
  result = (float) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Vector3_z_set(void * jarg1, float jarg2) {
  Vector3 *arg1 = (Vector3 *) 0 ;
  float arg2 ;
  
  arg1 = (Vector3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_Vector3_z_get(void * jarg1) {
  float jresult ;
  Vector3 *arg1 = (Vector3 *) 0 ;
  float result;
  
  arg1 = (Vector3 *)jarg1; 
  result = (float) ((arg1)->z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Vector3(void * jarg1) {
  Vector3 *arg1 = (Vector3 *) 0 ;
  
  arg1 = (Vector3 *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_SetMass(void * jarg1, float jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  float arg2 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->SetMass(arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_Particle_GetMass(void * jarg1) {
  float jresult ;
  Particle *arg1 = (Particle *) 0 ;
  float result;
  
  arg1 = (Particle *)jarg1; 
  result = (float)((Particle const *)arg1)->GetMass();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_Integrate(void * jarg1, float jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  float arg2 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->Integrate(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_AddForce(void * jarg1, void * jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *arg2 = 0 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (Vector3 *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Vector3 const & type is null", 0);
    return ;
  } 
  (arg1)->AddForce((Vector3 const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_position_set(void * jarg1, void * jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *arg2 = (Vector3 *) 0 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (Vector3 *)jarg2; 
  if (arg1) (arg1)->position = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Particle_position_get(void * jarg1) {
  void * jresult ;
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *result = 0 ;
  
  arg1 = (Particle *)jarg1; 
  result = (Vector3 *)& ((arg1)->position);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_velocity_set(void * jarg1, void * jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *arg2 = (Vector3 *) 0 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (Vector3 *)jarg2; 
  if (arg1) (arg1)->velocity = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Particle_velocity_get(void * jarg1) {
  void * jresult ;
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *result = 0 ;
  
  arg1 = (Particle *)jarg1; 
  result = (Vector3 *)& ((arg1)->velocity);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_acceleration_set(void * jarg1, void * jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *arg2 = (Vector3 *) 0 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (Vector3 *)jarg2; 
  if (arg1) (arg1)->acceleration = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Particle_acceleration_get(void * jarg1) {
  void * jresult ;
  Particle *arg1 = (Particle *) 0 ;
  Vector3 *result = 0 ;
  
  arg1 = (Particle *)jarg1; 
  result = (Vector3 *)& ((arg1)->acceleration);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Particle_damping_set(void * jarg1, float jarg2) {
  Particle *arg1 = (Particle *) 0 ;
  float arg2 ;
  
  arg1 = (Particle *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->damping = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_Particle_damping_get(void * jarg1) {
  float jresult ;
  Particle *arg1 = (Particle *) 0 ;
  float result;
  
  arg1 = (Particle *)jarg1; 
  result = (float) ((arg1)->damping);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Particle() {
  void * jresult ;
  Particle *result = 0 ;
  
  result = (Particle *)new Particle();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Particle(void * jarg1) {
  Particle *arg1 = (Particle *) 0 ;
  
  arg1 = (Particle *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_Resolve(void * jarg1, float jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (float)jarg2; 
  (arg1)->Resolve(arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleContact_CalculateSeparatingVelocity(void * jarg1) {
  float jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float result;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (float)((ParticleContact const *)arg1)->CalculateSeparatingVelocity();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_restitutionCoefficient_set(void * jarg1, float jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->restitutionCoefficient = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleContact_restitutionCoefficient_get(void * jarg1) {
  float jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float result;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (float) ((arg1)->restitutionCoefficient);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_penetrationDepth_set(void * jarg1, float jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->penetrationDepth = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleContact_penetrationDepth_get(void * jarg1) {
  float jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  float result;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (float) ((arg1)->penetrationDepth);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_contactNormal_set(void * jarg1, void * jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Vector3 *arg2 = (Vector3 *) 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (Vector3 *)jarg2; 
  if (arg1) (arg1)->contactNormal = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleContact_contactNormal_get(void * jarg1) {
  void * jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Vector3 *result = 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (Vector3 *)& ((arg1)->contactNormal);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_particle0_set(void * jarg1, void * jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Particle *arg2 = (Particle *) 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (Particle *)jarg2; 
  if (arg1) (arg1)->particle0 = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleContact_particle0_get(void * jarg1) {
  void * jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Particle *result = 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (Particle *) ((arg1)->particle0);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleContact_particle1_set(void * jarg1, void * jarg2) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Particle *arg2 = (Particle *) 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  arg2 = (Particle *)jarg2; 
  if (arg1) (arg1)->particle1 = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleContact_particle1_get(void * jarg1) {
  void * jresult ;
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  Particle *result = 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  result = (Particle *) ((arg1)->particle1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ParticleContact() {
  void * jresult ;
  ParticleContact *result = 0 ;
  
  result = (ParticleContact *)new ParticleContact();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParticleContact(void * jarg1) {
  ParticleContact *arg1 = (ParticleContact *) 0 ;
  
  arg1 = (ParticleContact *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParticleCable_AddContact(void * jarg1, void * jarg2, unsigned int jarg3) {
  unsigned int jresult ;
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  ParticleContact *arg2 = (ParticleContact *) 0 ;
  unsigned int arg3 ;
  bool result;
  
  arg1 = (ParticleCable *)jarg1; 
  arg2 = (ParticleContact *)jarg2; 
  arg3 = (unsigned int)jarg3; 
  result = (bool)((ParticleCable const *)arg1)->AddContact(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCable_maxLength_set(void * jarg1, float jarg2) {
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleCable *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->maxLength = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleCable_maxLength_get(void * jarg1) {
  float jresult ;
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  float result;
  
  arg1 = (ParticleCable *)jarg1; 
  result = (float) ((arg1)->maxLength);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCable_restitutionCoefficient_set(void * jarg1, float jarg2) {
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleCable *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->restitutionCoefficient = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleCable_restitutionCoefficient_get(void * jarg1) {
  float jresult ;
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  float result;
  
  arg1 = (ParticleCable *)jarg1; 
  result = (float) ((arg1)->restitutionCoefficient);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCable_particle0_set(void * jarg1, void * jarg2) {
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  Particle *arg2 = (Particle *) 0 ;
  
  arg1 = (ParticleCable *)jarg1; 
  arg2 = (Particle *)jarg2; 
  if (arg1) (arg1)->particle0 = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleCable_particle0_get(void * jarg1) {
  void * jresult ;
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  Particle *result = 0 ;
  
  arg1 = (ParticleCable *)jarg1; 
  result = (Particle *) ((arg1)->particle0);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCable_particle1_set(void * jarg1, void * jarg2) {
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  Particle *arg2 = (Particle *) 0 ;
  
  arg1 = (ParticleCable *)jarg1; 
  arg2 = (Particle *)jarg2; 
  if (arg1) (arg1)->particle1 = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleCable_particle1_get(void * jarg1) {
  void * jresult ;
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  Particle *result = 0 ;
  
  arg1 = (ParticleCable *)jarg1; 
  result = (Particle *) ((arg1)->particle1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ParticleCable() {
  void * jresult ;
  ParticleCable *result = 0 ;
  
  result = (ParticleCable *)new ParticleCable();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParticleCable(void * jarg1) {
  ParticleCable *arg1 = (ParticleCable *) 0 ;
  
  arg1 = (ParticleCable *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParticleCableConstraint_AddContact(void * jarg1, void * jarg2, unsigned int jarg3) {
  unsigned int jresult ;
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  ParticleContact *arg2 = (ParticleContact *) 0 ;
  unsigned int arg3 ;
  bool result;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  arg2 = (ParticleContact *)jarg2; 
  arg3 = (unsigned int)jarg3; 
  result = (bool)((ParticleCableConstraint const *)arg1)->AddContact(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCableConstraint_maxLength_set(void * jarg1, float jarg2) {
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->maxLength = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleCableConstraint_maxLength_get(void * jarg1) {
  float jresult ;
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  float result;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  result = (float) ((arg1)->maxLength);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCableConstraint_restitutionCoefficient_set(void * jarg1, float jarg2) {
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  float arg2 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->restitutionCoefficient = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ParticleCableConstraint_restitutionCoefficient_get(void * jarg1) {
  float jresult ;
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  float result;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  result = (float) ((arg1)->restitutionCoefficient);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCableConstraint_particle_set(void * jarg1, void * jarg2) {
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  Particle *arg2 = (Particle *) 0 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  arg2 = (Particle *)jarg2; 
  if (arg1) (arg1)->particle = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleCableConstraint_particle_get(void * jarg1) {
  void * jresult ;
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  Particle *result = 0 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  result = (Particle *) ((arg1)->particle);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ParticleCableConstraint_anchorPoint_set(void * jarg1, void * jarg2) {
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  Vector3 *arg2 = (Vector3 *) 0 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  arg2 = (Vector3 *)jarg2; 
  if (arg1) (arg1)->anchorPoint = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ParticleCableConstraint_anchorPoint_get(void * jarg1) {
  void * jresult ;
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  Vector3 *result = 0 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  result = (Vector3 *)& ((arg1)->anchorPoint);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ParticleCableConstraint() {
  void * jresult ;
  ParticleCableConstraint *result = 0 ;
  
  result = (ParticleCableConstraint *)new ParticleCableConstraint();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParticleCableConstraint(void * jarg1) {
  ParticleCableConstraint *arg1 = (ParticleCableConstraint *) 0 ;
  
  arg1 = (ParticleCableConstraint *)jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

