//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorParticleContact : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<ParticleContact>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorParticleContact(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorParticleContact obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorParticleContact() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_VectorParticleContact(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VectorParticleContact(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ParticleContact element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ParticleContact this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ParticleContact[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ParticleContact[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ParticleContact[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<ParticleContact> global::System.Collections.Generic.IEnumerable<ParticleContact>.GetEnumerator() {
    return new VectorParticleContactEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorParticleContactEnumerator(this);
  }

  public VectorParticleContactEnumerator GetEnumerator() {
    return new VectorParticleContactEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorParticleContactEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ParticleContact>
  {
    private VectorParticleContact collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorParticleContactEnumerator(VectorParticleContact collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ParticleContact Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ParticleContact)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_Clear(swigCPtr);
  }

  public void Add(ParticleContact x) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_Add(swigCPtr, ParticleContact.getCPtr(x));
  }

  private uint size() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_reserve(swigCPtr, n);
  }

  public VectorParticleContact() : this(PhysicsEngineForFunPINVOKE.new_VectorParticleContact__SWIG_0(), true) {
  }

  public VectorParticleContact(VectorParticleContact other) : this(PhysicsEngineForFunPINVOKE.new_VectorParticleContact__SWIG_1(VectorParticleContact.getCPtr(other)), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorParticleContact(int capacity) : this(PhysicsEngineForFunPINVOKE.new_VectorParticleContact__SWIG_2(capacity), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  private ParticleContact getitemcopy(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticleContact_getitemcopy(swigCPtr, index);
    ParticleContact ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParticleContact(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ParticleContact getitem(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticleContact_getitem(swigCPtr, index);
    ParticleContact ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParticleContact(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ParticleContact val) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_setitem(swigCPtr, index, ParticleContact.getCPtr(val));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorParticleContact values) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_AddRange(swigCPtr, VectorParticleContact.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorParticleContact GetRange(int index, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticleContact_GetRange(swigCPtr, index, count);
    VectorParticleContact ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorParticleContact(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ParticleContact x) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_Insert(swigCPtr, index, ParticleContact.getCPtr(x));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorParticleContact values) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_InsertRange(swigCPtr, index, VectorParticleContact.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_RemoveAt(swigCPtr, index);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_RemoveRange(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorParticleContact Repeat(ParticleContact value, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticleContact_Repeat(ParticleContact.getCPtr(value), count);
    VectorParticleContact ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorParticleContact(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_Reverse__SWIG_1(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorParticleContact values) {
    PhysicsEngineForFunPINVOKE.VectorParticleContact_SetRange(swigCPtr, index, VectorParticleContact.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(ParticleContact value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_Contains(swigCPtr, ParticleContact.getCPtr(value));
    return ret;
  }

  public int IndexOf(ParticleContact value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_IndexOf(swigCPtr, ParticleContact.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(ParticleContact value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_LastIndexOf(swigCPtr, ParticleContact.getCPtr(value));
    return ret;
  }

  public bool Remove(ParticleContact value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorParticleContact_Remove(swigCPtr, ParticleContact.getCPtr(value));
    return ret;
  }

}
