//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IParticleForceGenerator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IParticleForceGenerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IParticleForceGenerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IParticleForceGenerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_IParticleForceGenerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void UpdateForce(Particle particle, float duration) {
    if (SwigDerivedClassHasMethod("UpdateForce", swigMethodTypes0)) PhysicsEngineForFunPINVOKE.IParticleForceGenerator_UpdateForceSwigExplicitIParticleForceGenerator(swigCPtr, Particle.getCPtr(particle), duration); else PhysicsEngineForFunPINVOKE.IParticleForceGenerator_UpdateForce(swigCPtr, Particle.getCPtr(particle), duration);
  }

  public IParticleForceGenerator() : this(PhysicsEngineForFunPINVOKE.new_IParticleForceGenerator(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("UpdateForce", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIParticleForceGenerator_0(SwigDirectorUpdateForce);
    PhysicsEngineForFunPINVOKE.IParticleForceGenerator_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(IParticleForceGenerator));
    return hasDerivedMethod;
  }

  private void SwigDirectorUpdateForce(global::System.IntPtr particle, float duration) {
    UpdateForce((particle == global::System.IntPtr.Zero) ? null : new Particle(particle, false), duration);
  }

  public delegate void SwigDelegateIParticleForceGenerator_0(global::System.IntPtr particle, float duration);

  private SwigDelegateIParticleForceGenerator_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(Particle), typeof(float) };
}
