//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IParticleContactGenerator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IParticleContactGenerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IParticleContactGenerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IParticleContactGenerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_IParticleContactGenerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool AddContact(ParticleContact contact) {
    bool ret = (SwigDerivedClassHasMethod("AddContact", swigMethodTypes0) ? PhysicsEngineForFunPINVOKE.IParticleContactGenerator_AddContactSwigExplicitIParticleContactGenerator(swigCPtr, ParticleContact.getCPtr(contact)) : PhysicsEngineForFunPINVOKE.IParticleContactGenerator_AddContact(swigCPtr, ParticleContact.getCPtr(contact)));
    return ret;
  }

  public IParticleContactGenerator() : this(PhysicsEngineForFunPINVOKE.new_IParticleContactGenerator(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("AddContact", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIParticleContactGenerator_0(SwigDirectorAddContact);
    PhysicsEngineForFunPINVOKE.IParticleContactGenerator_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(IParticleContactGenerator));
    return hasDerivedMethod;
  }

  private bool SwigDirectorAddContact(global::System.IntPtr contact) {
    return AddContact((contact == global::System.IntPtr.Zero) ? null : new ParticleContact(contact, false));
  }

  public delegate bool SwigDelegateIParticleContactGenerator_0(global::System.IntPtr contact);

  private SwigDelegateIParticleContactGenerator_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ParticleContact) };
}
