//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ParticleForceRegistry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParticleForceRegistry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ParticleForceRegistry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParticleForceRegistry() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_ParticleForceRegistry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void Add(Particle particle, IParticleForceGenerator fg) {
    PhysicsEngineForFunPINVOKE.ParticleForceRegistry_Add(swigCPtr, Particle.getCPtr(particle), IParticleForceGenerator.getCPtr(fg));
  }

  public void Remove(Particle particle, IParticleForceGenerator fg) {
    PhysicsEngineForFunPINVOKE.ParticleForceRegistry_Remove(swigCPtr, Particle.getCPtr(particle), IParticleForceGenerator.getCPtr(fg));
  }

  public void Clear() {
    PhysicsEngineForFunPINVOKE.ParticleForceRegistry_Clear(swigCPtr);
  }

  public void UpdateForces(float duration) {
    PhysicsEngineForFunPINVOKE.ParticleForceRegistry_UpdateForces(swigCPtr, duration);
  }

  public ParticleForceRegistry() : this(PhysicsEngineForFunPINVOKE.new_ParticleForceRegistry(), true) {
  }

}
