/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_PhysicsEngineForFun_WRAP_H_
#define SWIG_PhysicsEngineForFun_WRAP_H_

class SwigDirector_IParticleContactGenerator : public IParticleContactGenerator, public Swig::Director {

public:
    SwigDirector_IParticleContactGenerator();
    virtual bool AddContact(ParticleContact *contact) const;

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackAddContact);

private:
    SWIG_Callback0_t swig_callbackAddContact;
    void swig_init_callbacks();
};

class SwigDirector_IParticleForceGenerator : public IParticleForceGenerator, public Swig::Director {

public:
    SwigDirector_IParticleForceGenerator();
    virtual void UpdateForce(Particle *particle, float duration);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, float);
    void swig_connect_director(SWIG_Callback0_t callbackUpdateForce);

private:
    SWIG_Callback0_t swig_callbackUpdateForce;
    void swig_init_callbacks();
};

class SwigDirector_IRigidBodyForceGenerator : public IRigidBodyForceGenerator, public Swig::Director {

public:
    SwigDirector_IRigidBodyForceGenerator();
    virtual void UpdateForce(RigidBody *body, float duration);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, float);
    void swig_connect_director(SWIG_Callback0_t callbackUpdateForce);

private:
    SWIG_Callback0_t swig_callbackUpdateForce;
    void swig_init_callbacks();
};


#endif
