//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RigidBodyForceRegistry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RigidBodyForceRegistry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RigidBodyForceRegistry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RigidBodyForceRegistry() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_RigidBodyForceRegistry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void Add(RigidBody body, IRigidBodyForceGenerator fg) {
    PhysicsEngineForFunPINVOKE.RigidBodyForceRegistry_Add(swigCPtr, RigidBody.getCPtr(body), IRigidBodyForceGenerator.getCPtr(fg));
  }

  public void Remove(RigidBody body, IRigidBodyForceGenerator fg) {
    PhysicsEngineForFunPINVOKE.RigidBodyForceRegistry_Remove(swigCPtr, RigidBody.getCPtr(body), IRigidBodyForceGenerator.getCPtr(fg));
  }

  public void Clear() {
    PhysicsEngineForFunPINVOKE.RigidBodyForceRegistry_Clear(swigCPtr);
  }

  public void UpdateForces(float duration) {
    PhysicsEngineForFunPINVOKE.RigidBodyForceRegistry_UpdateForces(swigCPtr, duration);
  }

  public RigidBodyForceRegistry() : this(PhysicsEngineForFunPINVOKE.new_RigidBodyForceRegistry(), true) {
  }

}
