//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorParticle : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<Particle>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorParticle(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorParticle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorParticle() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_VectorParticle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VectorParticle(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Particle element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Particle this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Particle[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Particle[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Particle[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Particle> global::System.Collections.Generic.IEnumerable<Particle>.GetEnumerator() {
    return new VectorParticleEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorParticleEnumerator(this);
  }

  public VectorParticleEnumerator GetEnumerator() {
    return new VectorParticleEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorParticleEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Particle>
  {
    private VectorParticle collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorParticleEnumerator(VectorParticle collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Particle Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Particle)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    PhysicsEngineForFunPINVOKE.VectorParticle_Clear(swigCPtr);
  }

  public void Add(Particle x) {
    PhysicsEngineForFunPINVOKE.VectorParticle_Add(swigCPtr, Particle.getCPtr(x));
  }

  private uint size() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorParticle_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorParticle_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PhysicsEngineForFunPINVOKE.VectorParticle_reserve(swigCPtr, n);
  }

  public VectorParticle() : this(PhysicsEngineForFunPINVOKE.new_VectorParticle__SWIG_0(), true) {
  }

  public VectorParticle(VectorParticle other) : this(PhysicsEngineForFunPINVOKE.new_VectorParticle__SWIG_1(VectorParticle.getCPtr(other)), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorParticle(int capacity) : this(PhysicsEngineForFunPINVOKE.new_VectorParticle__SWIG_2(capacity), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  private Particle getitemcopy(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticle_getitemcopy(swigCPtr, index);
    Particle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Particle(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Particle getitem(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticle_getitem(swigCPtr, index);
    Particle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Particle(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Particle val) {
    PhysicsEngineForFunPINVOKE.VectorParticle_setitem(swigCPtr, index, Particle.getCPtr(val));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorParticle values) {
    PhysicsEngineForFunPINVOKE.VectorParticle_AddRange(swigCPtr, VectorParticle.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorParticle GetRange(int index, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticle_GetRange(swigCPtr, index, count);
    VectorParticle ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorParticle(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Particle x) {
    PhysicsEngineForFunPINVOKE.VectorParticle_Insert(swigCPtr, index, Particle.getCPtr(x));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorParticle values) {
    PhysicsEngineForFunPINVOKE.VectorParticle_InsertRange(swigCPtr, index, VectorParticle.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PhysicsEngineForFunPINVOKE.VectorParticle_RemoveAt(swigCPtr, index);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorParticle_RemoveRange(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorParticle Repeat(Particle value, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorParticle_Repeat(Particle.getCPtr(value), count);
    VectorParticle ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorParticle(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PhysicsEngineForFunPINVOKE.VectorParticle_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorParticle_Reverse__SWIG_1(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorParticle values) {
    PhysicsEngineForFunPINVOKE.VectorParticle_SetRange(swigCPtr, index, VectorParticle.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Particle value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorParticle_Contains(swigCPtr, Particle.getCPtr(value));
    return ret;
  }

  public int IndexOf(Particle value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorParticle_IndexOf(swigCPtr, Particle.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Particle value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorParticle_LastIndexOf(swigCPtr, Particle.getCPtr(value));
    return ret;
  }

  public bool Remove(Particle value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorParticle_Remove(swigCPtr, Particle.getCPtr(value));
    return ret;
  }

}
