//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorIParticleContactGenerator : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<IParticleContactGenerator>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorIParticleContactGenerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorIParticleContactGenerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorIParticleContactGenerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PhysicsEngineForFunPINVOKE.delete_VectorIParticleContactGenerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VectorIParticleContactGenerator(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (IParticleContactGenerator element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public IParticleContactGenerator this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(IParticleContactGenerator[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(IParticleContactGenerator[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, IParticleContactGenerator[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<IParticleContactGenerator> global::System.Collections.Generic.IEnumerable<IParticleContactGenerator>.GetEnumerator() {
    return new VectorIParticleContactGeneratorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorIParticleContactGeneratorEnumerator(this);
  }

  public VectorIParticleContactGeneratorEnumerator GetEnumerator() {
    return new VectorIParticleContactGeneratorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorIParticleContactGeneratorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<IParticleContactGenerator>
  {
    private VectorIParticleContactGenerator collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorIParticleContactGeneratorEnumerator(VectorIParticleContactGenerator collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public IParticleContactGenerator Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (IParticleContactGenerator)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Clear(swigCPtr);
  }

  public void Add(IParticleContactGenerator x) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Add(swigCPtr, IParticleContactGenerator.getCPtr(x));
  }

  private uint size() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_reserve(swigCPtr, n);
  }

  public VectorIParticleContactGenerator() : this(PhysicsEngineForFunPINVOKE.new_VectorIParticleContactGenerator__SWIG_0(), true) {
  }

  public VectorIParticleContactGenerator(VectorIParticleContactGenerator other) : this(PhysicsEngineForFunPINVOKE.new_VectorIParticleContactGenerator__SWIG_1(VectorIParticleContactGenerator.getCPtr(other)), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorIParticleContactGenerator(int capacity) : this(PhysicsEngineForFunPINVOKE.new_VectorIParticleContactGenerator__SWIG_2(capacity), true) {
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  private IParticleContactGenerator getitemcopy(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_getitemcopy(swigCPtr, index);
    IParticleContactGenerator ret = (cPtr == global::System.IntPtr.Zero) ? null : new IParticleContactGenerator(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private IParticleContactGenerator getitem(int index) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_getitem(swigCPtr, index);
    IParticleContactGenerator ret = (cPtr == global::System.IntPtr.Zero) ? null : new IParticleContactGenerator(cPtr, false);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, IParticleContactGenerator val) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_setitem(swigCPtr, index, IParticleContactGenerator.getCPtr(val));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorIParticleContactGenerator values) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_AddRange(swigCPtr, VectorIParticleContactGenerator.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorIParticleContactGenerator GetRange(int index, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_GetRange(swigCPtr, index, count);
    VectorIParticleContactGenerator ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorIParticleContactGenerator(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, IParticleContactGenerator x) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Insert(swigCPtr, index, IParticleContactGenerator.getCPtr(x));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorIParticleContactGenerator values) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_InsertRange(swigCPtr, index, VectorIParticleContactGenerator.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_RemoveAt(swigCPtr, index);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_RemoveRange(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorIParticleContactGenerator Repeat(IParticleContactGenerator value, int count) {
    global::System.IntPtr cPtr = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Repeat(IParticleContactGenerator.getCPtr(value), count);
    VectorIParticleContactGenerator ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorIParticleContactGenerator(cPtr, true);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Reverse__SWIG_1(swigCPtr, index, count);
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorIParticleContactGenerator values) {
    PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_SetRange(swigCPtr, index, VectorIParticleContactGenerator.getCPtr(values));
    if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(IParticleContactGenerator value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Contains(swigCPtr, IParticleContactGenerator.getCPtr(value));
    return ret;
  }

  public int IndexOf(IParticleContactGenerator value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_IndexOf(swigCPtr, IParticleContactGenerator.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(IParticleContactGenerator value) {
    int ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_LastIndexOf(swigCPtr, IParticleContactGenerator.getCPtr(value));
    return ret;
  }

  public bool Remove(IParticleContactGenerator value) {
    bool ret = PhysicsEngineForFunPINVOKE.VectorIParticleContactGenerator_Remove(swigCPtr, IParticleContactGenerator.getCPtr(value));
    return ret;
  }

}
