//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PhysicsEngineForFun
{
    public class BuoyancyOnRigidBody : IRigidBodyForceGenerator
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;

        internal BuoyancyOnRigidBody(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PhysicsEngineForFunPINVOKE.BuoyancyOnRigidBody_SWIGUpcast(cPtr), cMemoryOwn)
        {
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BuoyancyOnRigidBody obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~BuoyancyOnRigidBody()
        {
            Dispose();
        }

        public override void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        PhysicsEngineForFunPINVOKE.delete_BuoyancyOnRigidBody(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
                base.Dispose();
            }
        }

        public BuoyancyOnRigidBody(Vector3 centerOfBuoyancy, float maxDepth, float volume, float waterSurfaceHeight, float liquidDensity) : this(PhysicsEngineForFunPINVOKE.new_BuoyancyOnRigidBody__SWIG_0(Vector3.getCPtr(centerOfBuoyancy), maxDepth, volume, waterSurfaceHeight, liquidDensity), true)
        {
            if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
        }

        public BuoyancyOnRigidBody(Vector3 centerOfBuoyancy, float maxDepth, float volume, float waterSurfaceHeight) : this(PhysicsEngineForFunPINVOKE.new_BuoyancyOnRigidBody__SWIG_1(Vector3.getCPtr(centerOfBuoyancy), maxDepth, volume, waterSurfaceHeight), true)
        {
            if (PhysicsEngineForFunPINVOKE.SWIGPendingException.Pending) throw PhysicsEngineForFunPINVOKE.SWIGPendingException.Retrieve();
        }

        public override void UpdateForce(RigidBody body, float duration)
        {
            PhysicsEngineForFunPINVOKE.BuoyancyOnRigidBody_UpdateForce(swigCPtr, RigidBody.getCPtr(body), duration);
        }

    }
}